// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts/generate-protobus-setup.mjs
import * as proto from "@shared/proto/index"
import { Callbacks, ProtoBusClient } from "./protobus-client-base"

export class AccountServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.AccountService"
	static async accountLoginClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.String> {
		return AccountServiceClient.makeUnaryRequest(
			"accountLoginClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
	static async accountLogoutClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"accountLogoutClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static subscribeToAuthStatusUpdate(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.AuthState>,
	): () => void {
		return AccountServiceClient.makeStreamingRequest(
			"subscribeToAuthStatusUpdate",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.AuthState.fromJSON,
			callbacks,
		)
	}
	static async authStateChanged(request: proto.codemarie.AuthStateChangedRequest): Promise<proto.codemarie.AuthState> {
		return AccountServiceClient.makeUnaryRequest(
			"authStateChanged",
			request,
			proto.codemarie.AuthStateChangedRequest.toJSON,
			proto.codemarie.AuthState.fromJSON,
		)
	}
	static async getUserCredits(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.UserCreditsData> {
		return AccountServiceClient.makeUnaryRequest(
			"getUserCredits",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.UserCreditsData.fromJSON,
		)
	}
	static async getOrganizationCredits(
		request: proto.codemarie.GetOrganizationCreditsRequest,
	): Promise<proto.codemarie.OrganizationCreditsData> {
		return AccountServiceClient.makeUnaryRequest(
			"getOrganizationCredits",
			request,
			proto.codemarie.GetOrganizationCreditsRequest.toJSON,
			proto.codemarie.OrganizationCreditsData.fromJSON,
		)
	}
	static async getUserOrganizations(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.UserOrganizationsResponse> {
		return AccountServiceClient.makeUnaryRequest(
			"getUserOrganizations",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.UserOrganizationsResponse.fromJSON,
		)
	}
	static async setUserOrganization(request: proto.codemarie.UserOrganizationUpdateRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"setUserOrganization",
			request,
			proto.codemarie.UserOrganizationUpdateRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openrouterAuthClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openrouterAuthClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async requestyAuthClicked(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"requestyAuthClicked",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async hicapAuthClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"hicapAuthClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async getRedirectUrl(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.String> {
		return AccountServiceClient.makeUnaryRequest(
			"getRedirectUrl",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
	static async openAiCodexSignIn(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openAiCodexSignIn",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openAiCodexSignOut(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openAiCodexSignOut",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.BrowserService"
	static async getBrowserConnectionInfo(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.BrowserConnectionInfo> {
		return BrowserServiceClient.makeUnaryRequest(
			"getBrowserConnectionInfo",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.BrowserConnectionInfo.fromJSON,
		)
	}
	static async testBrowserConnection(request: proto.codemarie.StringRequest): Promise<proto.codemarie.BrowserConnection> {
		return BrowserServiceClient.makeUnaryRequest(
			"testBrowserConnection",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.BrowserConnection.fromJSON,
		)
	}
	static async discoverBrowser(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.BrowserConnection> {
		return BrowserServiceClient.makeUnaryRequest(
			"discoverBrowser",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.BrowserConnection.fromJSON,
		)
	}
	static async getDetectedChromePath(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.ChromePath> {
		return BrowserServiceClient.makeUnaryRequest(
			"getDetectedChromePath",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.ChromePath.fromJSON,
		)
	}
	static async relaunchChromeDebugMode(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.String> {
		return BrowserServiceClient.makeUnaryRequest(
			"relaunchChromeDebugMode",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.CheckpointsService"
	static async checkpointDiff(request: proto.codemarie.Int64Request): Promise<proto.codemarie.Empty> {
		return CheckpointsServiceClient.makeUnaryRequest(
			"checkpointDiff",
			request,
			proto.codemarie.Int64Request.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async checkpointRestore(request: proto.codemarie.CheckpointRestoreRequest): Promise<proto.codemarie.Empty> {
		return CheckpointsServiceClient.makeUnaryRequest(
			"checkpointRestore",
			request,
			proto.codemarie.CheckpointRestoreRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static subscribeToCheckpoints(
		request: proto.codemarie.CheckpointSubscriptionRequest,
		callbacks: Callbacks<proto.codemarie.CheckpointEvent>,
	): () => void {
		return CheckpointsServiceClient.makeStreamingRequest(
			"subscribeToCheckpoints",
			request,
			proto.codemarie.CheckpointSubscriptionRequest.toJSON,
			proto.codemarie.CheckpointEvent.fromJSON,
			callbacks,
		)
	}
	static async getCwdHash(request: proto.codemarie.StringArrayRequest): Promise<proto.codemarie.PathHashMap> {
		return CheckpointsServiceClient.makeUnaryRequest(
			"getCwdHash",
			request,
			proto.codemarie.StringArrayRequest.toJSON,
			proto.codemarie.PathHashMap.fromJSON,
		)
	}
}
export class CommandsServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.CommandsService"
	static async addToCodemarie(request: proto.codemarie.CommandContext): Promise<proto.codemarie.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"addToCodemarie",
			request,
			proto.codemarie.CommandContext.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async fixWithCodemarie(request: proto.codemarie.CommandContext): Promise<proto.codemarie.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"fixWithCodemarie",
			request,
			proto.codemarie.CommandContext.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async explainWithCodemarie(request: proto.codemarie.CommandContext): Promise<proto.codemarie.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"explainWithCodemarie",
			request,
			proto.codemarie.CommandContext.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async improveWithCodemarie(request: proto.codemarie.CommandContext): Promise<proto.codemarie.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"improveWithCodemarie",
			request,
			proto.codemarie.CommandContext.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.FileService"
	static async copyToClipboard(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"copyToClipboard",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openFile(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFile",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openImage(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openImage",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openMention(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openMention",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async deleteRuleFile(request: proto.codemarie.RuleFileRequest): Promise<proto.codemarie.RuleFile> {
		return FileServiceClient.makeUnaryRequest(
			"deleteRuleFile",
			request,
			proto.codemarie.RuleFileRequest.toJSON,
			proto.codemarie.RuleFile.fromJSON,
		)
	}
	static async createRuleFile(request: proto.codemarie.RuleFileRequest): Promise<proto.codemarie.RuleFile> {
		return FileServiceClient.makeUnaryRequest(
			"createRuleFile",
			request,
			proto.codemarie.RuleFileRequest.toJSON,
			proto.codemarie.RuleFile.fromJSON,
		)
	}
	static async searchCommits(request: proto.codemarie.StringRequest): Promise<proto.codemarie.GitCommits> {
		return FileServiceClient.makeUnaryRequest(
			"searchCommits",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.GitCommits.fromJSON,
		)
	}
	static async selectFiles(request: proto.codemarie.BooleanRequest): Promise<proto.codemarie.StringArrays> {
		return FileServiceClient.makeUnaryRequest(
			"selectFiles",
			request,
			proto.codemarie.BooleanRequest.toJSON,
			proto.codemarie.StringArrays.fromJSON,
		)
	}
	static async getRelativePaths(request: proto.codemarie.RelativePathsRequest): Promise<proto.codemarie.RelativePaths> {
		return FileServiceClient.makeUnaryRequest(
			"getRelativePaths",
			request,
			proto.codemarie.RelativePathsRequest.toJSON,
			proto.codemarie.RelativePaths.fromJSON,
		)
	}
	static async searchFiles(request: proto.codemarie.FileSearchRequest): Promise<proto.codemarie.FileSearchResults> {
		return FileServiceClient.makeUnaryRequest(
			"searchFiles",
			request,
			proto.codemarie.FileSearchRequest.toJSON,
			proto.codemarie.FileSearchResults.fromJSON,
		)
	}
	static async toggleCodemarieRule(
		request: proto.codemarie.ToggleCodemarieRuleRequest,
	): Promise<proto.codemarie.ToggleCodemarieRules> {
		return FileServiceClient.makeUnaryRequest(
			"toggleCodemarieRule",
			request,
			proto.codemarie.ToggleCodemarieRuleRequest.toJSON,
			proto.codemarie.ToggleCodemarieRules.fromJSON,
		)
	}
	static async toggleCursorRule(
		request: proto.codemarie.ToggleCursorRuleRequest,
	): Promise<proto.codemarie.CodemarieRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleCursorRule",
			request,
			proto.codemarie.ToggleCursorRuleRequest.toJSON,
			proto.codemarie.CodemarieRulesToggles.fromJSON,
		)
	}
	static async toggleWindsurfRule(
		request: proto.codemarie.ToggleWindsurfRuleRequest,
	): Promise<proto.codemarie.CodemarieRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleWindsurfRule",
			request,
			proto.codemarie.ToggleWindsurfRuleRequest.toJSON,
			proto.codemarie.CodemarieRulesToggles.fromJSON,
		)
	}
	static async toggleAgentsRule(
		request: proto.codemarie.ToggleAgentsRuleRequest,
	): Promise<proto.codemarie.CodemarieRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleAgentsRule",
			request,
			proto.codemarie.ToggleAgentsRuleRequest.toJSON,
			proto.codemarie.CodemarieRulesToggles.fromJSON,
		)
	}
	static async refreshRules(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.RefreshedRules> {
		return FileServiceClient.makeUnaryRequest(
			"refreshRules",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.RefreshedRules.fromJSON,
		)
	}
	static async openDiskConversationHistory(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openDiskConversationHistory",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async toggleWorkflow(request: proto.codemarie.ToggleWorkflowRequest): Promise<proto.codemarie.CodemarieRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleWorkflow",
			request,
			proto.codemarie.ToggleWorkflowRequest.toJSON,
			proto.codemarie.CodemarieRulesToggles.fromJSON,
		)
	}
	static async ifFileExistsRelativePath(request: proto.codemarie.StringRequest): Promise<proto.codemarie.BooleanResponse> {
		return FileServiceClient.makeUnaryRequest(
			"ifFileExistsRelativePath",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.BooleanResponse.fromJSON,
		)
	}
	static async openFileRelativePath(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFileRelativePath",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openFocusChainFile(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFocusChainFile",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async refreshHooks(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.HooksToggles> {
		return FileServiceClient.makeUnaryRequest(
			"refreshHooks",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.HooksToggles.fromJSON,
		)
	}
	static async toggleHook(request: proto.codemarie.ToggleHookRequest): Promise<proto.codemarie.ToggleHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"toggleHook",
			request,
			proto.codemarie.ToggleHookRequest.toJSON,
			proto.codemarie.ToggleHookResponse.fromJSON,
		)
	}
	static async createHook(request: proto.codemarie.CreateHookRequest): Promise<proto.codemarie.CreateHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"createHook",
			request,
			proto.codemarie.CreateHookRequest.toJSON,
			proto.codemarie.CreateHookResponse.fromJSON,
		)
	}
	static async deleteHook(request: proto.codemarie.DeleteHookRequest): Promise<proto.codemarie.DeleteHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"deleteHook",
			request,
			proto.codemarie.DeleteHookRequest.toJSON,
			proto.codemarie.DeleteHookResponse.fromJSON,
		)
	}
	static async refreshSkills(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.RefreshedSkills> {
		return FileServiceClient.makeUnaryRequest(
			"refreshSkills",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.RefreshedSkills.fromJSON,
		)
	}
	static async toggleSkill(request: proto.codemarie.ToggleSkillRequest): Promise<proto.codemarie.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleSkill",
			request,
			proto.codemarie.ToggleSkillRequest.toJSON,
			proto.codemarie.SkillsToggles.fromJSON,
		)
	}
	static async createSkillFile(request: proto.codemarie.CreateSkillRequest): Promise<proto.codemarie.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"createSkillFile",
			request,
			proto.codemarie.CreateSkillRequest.toJSON,
			proto.codemarie.SkillsToggles.fromJSON,
		)
	}
	static async deleteSkillFile(request: proto.codemarie.DeleteSkillRequest): Promise<proto.codemarie.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"deleteSkillFile",
			request,
			proto.codemarie.DeleteSkillRequest.toJSON,
			proto.codemarie.SkillsToggles.fromJSON,
		)
	}
}
export class McpServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.McpService"
	static async toggleMcpServer(request: proto.codemarie.ToggleMcpServerRequest): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"toggleMcpServer",
			request,
			proto.codemarie.ToggleMcpServerRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async updateMcpTimeout(request: proto.codemarie.UpdateMcpTimeoutRequest): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"updateMcpTimeout",
			request,
			proto.codemarie.UpdateMcpTimeoutRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async addRemoteMcpServer(request: proto.codemarie.AddRemoteMcpServerRequest): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"addRemoteMcpServer",
			request,
			proto.codemarie.AddRemoteMcpServerRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async downloadMcp(request: proto.codemarie.StringRequest): Promise<proto.codemarie.McpDownloadResponse> {
		return McpServiceClient.makeUnaryRequest(
			"downloadMcp",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.McpDownloadResponse.fromJSON,
		)
	}
	static async restartMcpServer(request: proto.codemarie.StringRequest): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"restartMcpServer",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async deleteMcpServer(request: proto.codemarie.StringRequest): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"deleteMcpServer",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async toggleToolAutoApprove(
		request: proto.codemarie.ToggleToolAutoApproveRequest,
	): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"toggleToolAutoApprove",
			request,
			proto.codemarie.ToggleToolAutoApproveRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static async refreshMcpMarketplace(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.McpMarketplaceCatalog> {
		return McpServiceClient.makeUnaryRequest(
			"refreshMcpMarketplace",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.McpMarketplaceCatalog.fromJSON,
		)
	}
	static async openMcpSettings(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return McpServiceClient.makeUnaryRequest(
			"openMcpSettings",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async authenticateMcpServer(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return McpServiceClient.makeUnaryRequest(
			"authenticateMcpServer",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static subscribeToMcpMarketplaceCatalog(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.McpMarketplaceCatalog>,
	): () => void {
		return McpServiceClient.makeStreamingRequest(
			"subscribeToMcpMarketplaceCatalog",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.McpMarketplaceCatalog.fromJSON,
			callbacks,
		)
	}
	static async getLatestMcpServers(request: proto.codemarie.Empty): Promise<proto.codemarie.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"getLatestMcpServers",
			request,
			proto.codemarie.Empty.toJSON,
			proto.codemarie.McpServers.fromJSON,
		)
	}
	static subscribeToMcpServers(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.McpServers>,
	): () => void {
		return McpServiceClient.makeStreamingRequest(
			"subscribeToMcpServers",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.McpServers.fromJSON,
			callbacks,
		)
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.ModelsService"
	static async getOllamaModels(request: proto.codemarie.StringRequest): Promise<proto.codemarie.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getOllamaModels",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.StringArray.fromJSON,
		)
	}
	static async getLmStudioModels(request: proto.codemarie.StringRequest): Promise<proto.codemarie.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getLmStudioModels",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.StringArray.fromJSON,
		)
	}
	static async getVsCodeLmModels(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.VsCodeLmModelsArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getVsCodeLmModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.VsCodeLmModelsArray.fromJSON,
		)
	}
	static async refreshOpenRouterModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOpenRouterModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshCodemarieRecommendedModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.CodemarieRecommendedModelsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshCodemarieRecommendedModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.CodemarieRecommendedModelsResponse.fromJSON,
		)
	}
	static async refreshCodemarieModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshCodemarieModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshHuggingFaceModels(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshHuggingFaceModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshOpenAiModels(request: proto.codemarie.OpenAiModelsRequest): Promise<proto.codemarie.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOpenAiModels",
			request,
			proto.codemarie.OpenAiModelsRequest.toJSON,
			proto.codemarie.StringArray.fromJSON,
		)
	}
	static async refreshRequestyModels(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshRequestyModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshHicapModels(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshHicapModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshLiteLlmModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshLiteLlmModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static subscribeToOpenRouterModels(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.OpenRouterCompatibleModelInfo>,
	): () => void {
		return ModelsServiceClient.makeStreamingRequest(
			"subscribeToOpenRouterModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		)
	}
	static subscribeToLiteLlmModels(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.OpenRouterCompatibleModelInfo>,
	): () => void {
		return ModelsServiceClient.makeStreamingRequest(
			"subscribeToLiteLlmModels",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		)
	}
	static async updateApiConfigurationProto(
		request: proto.codemarie.UpdateApiConfigurationRequest,
	): Promise<proto.codemarie.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfigurationProto",
			request,
			proto.codemarie.UpdateApiConfigurationRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateApiConfiguration(
		request: proto.codemarie.UpdateApiConfigurationRequestNew,
	): Promise<proto.codemarie.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfiguration",
			request,
			proto.codemarie.UpdateApiConfigurationRequestNew.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateApiConfigurationPartial(
		request: proto.codemarie.UpdateApiConfigurationPartialRequest,
	): Promise<proto.codemarie.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfigurationPartial",
			request,
			proto.codemarie.UpdateApiConfigurationPartialRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async refreshGroqModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshGroqModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshBasetenModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshBasetenModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async getSapAiCoreModels(
		request: proto.codemarie.SapAiCoreModelsRequest,
	): Promise<proto.codemarie.SapAiCoreModelsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"getSapAiCoreModels",
			request,
			proto.codemarie.SapAiCoreModelsRequest.toJSON,
			proto.codemarie.SapAiCoreModelsResponse.fromJSON,
		)
	}
	static async refreshOcaModels(request: proto.codemarie.StringRequest): Promise<proto.codemarie.OcaCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOcaModels",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.OcaCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshVercelAiGatewayModelsRpc(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshVercelAiGatewayModelsRpc",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
}
export class OcaAccountServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.OcaAccountService"
	static async ocaAccountLoginClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.String> {
		return OcaAccountServiceClient.makeUnaryRequest(
			"ocaAccountLoginClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
	static async ocaAccountLogoutClicked(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return OcaAccountServiceClient.makeUnaryRequest(
			"ocaAccountLogoutClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static ocaSubscribeToAuthStatusUpdate(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.OcaAuthState>,
	): () => void {
		return OcaAccountServiceClient.makeStreamingRequest(
			"ocaSubscribeToAuthStatusUpdate",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.OcaAuthState.fromJSON,
			callbacks,
		)
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.SlashService"
	static async reportBug(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return SlashServiceClient.makeUnaryRequest(
			"reportBug",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async condense(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return SlashServiceClient.makeUnaryRequest(
			"condense",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async getAvailableSlashCommands(
		request: proto.codemarie.EmptyRequest,
	): Promise<proto.codemarie.SlashCommandsResponse> {
		return SlashServiceClient.makeUnaryRequest(
			"getAvailableSlashCommands",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.SlashCommandsResponse.fromJSON,
		)
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.StateService"
	static async getLatestState(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.State> {
		return StateServiceClient.makeUnaryRequest(
			"getLatestState",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.State.fromJSON,
		)
	}
	static async updateTerminalConnectionTimeout(
		request: proto.codemarie.UpdateTerminalConnectionTimeoutRequest,
	): Promise<proto.codemarie.UpdateTerminalConnectionTimeoutResponse> {
		return StateServiceClient.makeUnaryRequest(
			"updateTerminalConnectionTimeout",
			request,
			proto.codemarie.UpdateTerminalConnectionTimeoutRequest.toJSON,
			proto.codemarie.UpdateTerminalConnectionTimeoutResponse.fromJSON,
		)
	}
	static async updateTerminalReuseEnabled(request: proto.codemarie.BooleanRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTerminalReuseEnabled",
			request,
			proto.codemarie.BooleanRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async getAvailableTerminalProfiles(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.TerminalProfiles> {
		return StateServiceClient.makeUnaryRequest(
			"getAvailableTerminalProfiles",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.TerminalProfiles.fromJSON,
		)
	}
	static subscribeToState(request: proto.codemarie.EmptyRequest, callbacks: Callbacks<proto.codemarie.State>): () => void {
		return StateServiceClient.makeStreamingRequest(
			"subscribeToState",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.State.fromJSON,
			callbacks,
		)
	}
	static async toggleFavoriteModel(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"toggleFavoriteModel",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async resetState(request: proto.codemarie.ResetStateRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"resetState",
			request,
			proto.codemarie.ResetStateRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async togglePlanActModeProto(request: proto.codemarie.TogglePlanActModeRequest): Promise<proto.codemarie.Boolean> {
		return StateServiceClient.makeUnaryRequest(
			"togglePlanActModeProto",
			request,
			proto.codemarie.TogglePlanActModeRequest.toJSON,
			proto.codemarie.Boolean.fromJSON,
		)
	}
	static async updateAutoApprovalSettings(
		request: proto.codemarie.AutoApprovalSettingsRequest,
	): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateAutoApprovalSettings",
			request,
			proto.codemarie.AutoApprovalSettingsRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateSettings(request: proto.codemarie.UpdateSettingsRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateSettings",
			request,
			proto.codemarie.UpdateSettingsRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateSettingsCli(request: proto.codemarie.UpdateSettingsRequestCli): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateSettingsCli",
			request,
			proto.codemarie.UpdateSettingsRequestCli.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateTaskSettings(request: proto.codemarie.UpdateTaskSettingsRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTaskSettings",
			request,
			proto.codemarie.UpdateTaskSettingsRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateTelemetrySetting(request: proto.codemarie.TelemetrySettingRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTelemetrySetting",
			request,
			proto.codemarie.TelemetrySettingRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async captureOnboardingProgress(request: proto.codemarie.OnboardingProgressRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"captureOnboardingProgress",
			request,
			proto.codemarie.OnboardingProgressRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async setWelcomeViewCompleted(request: proto.codemarie.BooleanRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"setWelcomeViewCompleted",
			request,
			proto.codemarie.BooleanRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateInfoBannerVersion(request: proto.codemarie.Int64Request): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateInfoBannerVersion",
			request,
			proto.codemarie.Int64Request.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateModelBannerVersion(request: proto.codemarie.Int64Request): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateModelBannerVersion",
			request,
			proto.codemarie.Int64Request.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async updateCliBannerVersion(request: proto.codemarie.Int64Request): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateCliBannerVersion",
			request,
			proto.codemarie.Int64Request.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async dismissBanner(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"dismissBanner",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async trackBannerEvent(request: proto.codemarie.TrackBannerEventRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"trackBannerEvent",
			request,
			proto.codemarie.TrackBannerEventRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async installCodemarieCli(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"installCodemarieCli",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async checkCliInstallation(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Boolean> {
		return StateServiceClient.makeUnaryRequest(
			"checkCliInstallation",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Boolean.fromJSON,
		)
	}
	static async getProcessInfo(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.ProcessInfo> {
		return StateServiceClient.makeUnaryRequest(
			"getProcessInfo",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.ProcessInfo.fromJSON,
		)
	}
	static async flushPendingState(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"flushPendingState",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async refreshRemoteConfig(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"refreshRemoteConfig",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async testOtelConnection(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.TestConnectionResult> {
		return StateServiceClient.makeUnaryRequest(
			"testOtelConnection",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.TestConnectionResult.fromJSON,
		)
	}
	static async testPromptUploading(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.TestConnectionResult> {
		return StateServiceClient.makeUnaryRequest(
			"testPromptUploading",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.TestConnectionResult.fromJSON,
		)
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.TaskService"
	static async cancelTask(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"cancelTask",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async cancelBackgroundCommand(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"cancelBackgroundCommand",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async clearTask(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"clearTask",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async getTotalTasksSize(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Int64> {
		return TaskServiceClient.makeUnaryRequest(
			"getTotalTasksSize",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Int64.fromJSON,
		)
	}
	static async deleteTasksWithIds(request: proto.codemarie.StringArrayRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"deleteTasksWithIds",
			request,
			proto.codemarie.StringArrayRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async newTask(request: proto.codemarie.NewTaskRequest): Promise<proto.codemarie.String> {
		return TaskServiceClient.makeUnaryRequest(
			"newTask",
			request,
			proto.codemarie.NewTaskRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
	static async showTaskWithId(request: proto.codemarie.StringRequest): Promise<proto.codemarie.TaskResponse> {
		return TaskServiceClient.makeUnaryRequest(
			"showTaskWithId",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.TaskResponse.fromJSON,
		)
	}
	static async exportTaskWithId(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"exportTaskWithId",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async toggleTaskFavorite(request: proto.codemarie.TaskFavoriteRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"toggleTaskFavorite",
			request,
			proto.codemarie.TaskFavoriteRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async getTaskHistory(request: proto.codemarie.GetTaskHistoryRequest): Promise<proto.codemarie.TaskHistoryArray> {
		return TaskServiceClient.makeUnaryRequest(
			"getTaskHistory",
			request,
			proto.codemarie.GetTaskHistoryRequest.toJSON,
			proto.codemarie.TaskHistoryArray.fromJSON,
		)
	}
	static async askResponse(request: proto.codemarie.AskResponseRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"askResponse",
			request,
			proto.codemarie.AskResponseRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async taskFeedback(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"taskFeedback",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async taskCompletionViewChanges(request: proto.codemarie.Int64Request): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"taskCompletionViewChanges",
			request,
			proto.codemarie.Int64Request.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async executeQuickWin(request: proto.codemarie.ExecuteQuickWinRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"executeQuickWin",
			request,
			proto.codemarie.ExecuteQuickWinRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async deleteAllTaskHistory(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.DeleteAllTaskHistoryCount> {
		return TaskServiceClient.makeUnaryRequest(
			"deleteAllTaskHistory",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.DeleteAllTaskHistoryCount.fromJSON,
		)
	}
	static async explainChanges(request: proto.codemarie.ExplainChangesRequest): Promise<proto.codemarie.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"explainChanges",
			request,
			proto.codemarie.ExplainChangesRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.UiService"
	static async scrollToSettings(request: proto.codemarie.StringRequest): Promise<proto.codemarie.KeyValuePair> {
		return UiServiceClient.makeUnaryRequest(
			"scrollToSettings",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.KeyValuePair.fromJSON,
		)
	}
	static async setTerminalExecutionMode(request: proto.codemarie.BooleanRequest): Promise<proto.codemarie.KeyValuePair> {
		return UiServiceClient.makeUnaryRequest(
			"setTerminalExecutionMode",
			request,
			proto.codemarie.BooleanRequest.toJSON,
			proto.codemarie.KeyValuePair.fromJSON,
		)
	}
	static async onDidShowAnnouncement(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Boolean> {
		return UiServiceClient.makeUnaryRequest(
			"onDidShowAnnouncement",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Boolean.fromJSON,
		)
	}
	static subscribeToAddToInput(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.String>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToAddToInput",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
			callbacks,
		)
	}
	static subscribeToMcpButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToMcpButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToHistoryButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToHistoryButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToChatButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToChatButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToAccountButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToAccountButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToSettingsButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToSettingsButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToWorktreesButtonClicked(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToWorktreesButtonClicked",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToPartialMessage(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.CodemarieMessage>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToPartialMessage",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.CodemarieMessage.fromJSON,
			callbacks,
		)
	}
	static async initializeWebview(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"initializeWebview",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static subscribeToRelinquishControl(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.Empty>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToRelinquishControl",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToShowWebview(
		request: proto.codemarie.EmptyRequest,
		callbacks: Callbacks<proto.codemarie.ShowWebviewEvent>,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToShowWebview",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.ShowWebviewEvent.fromJSON,
			callbacks,
		)
	}
	static async getWebviewHtml(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.String> {
		return UiServiceClient.makeUnaryRequest(
			"getWebviewHtml",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.String.fromJSON,
		)
	}
	static async openUrl(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"openUrl",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
	static async openWalkthrough(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"openWalkthrough",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.WebService"
	static async checkIsImageUrl(request: proto.codemarie.StringRequest): Promise<proto.codemarie.IsImageUrl> {
		return WebServiceClient.makeUnaryRequest(
			"checkIsImageUrl",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.IsImageUrl.fromJSON,
		)
	}
	static async fetchOpenGraphData(request: proto.codemarie.StringRequest): Promise<proto.codemarie.OpenGraphData> {
		return WebServiceClient.makeUnaryRequest(
			"fetchOpenGraphData",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.OpenGraphData.fromJSON,
		)
	}
	static async openInBrowser(request: proto.codemarie.StringRequest): Promise<proto.codemarie.Empty> {
		return WebServiceClient.makeUnaryRequest(
			"openInBrowser",
			request,
			proto.codemarie.StringRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
export class WorktreeServiceClient extends ProtoBusClient {
	static override serviceName = "codemarie.WorktreeService"
	static async listWorktrees(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.WorktreeList> {
		return WorktreeServiceClient.makeUnaryRequest(
			"listWorktrees",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.WorktreeList.fromJSON,
		)
	}
	static async createWorktree(request: proto.codemarie.CreateWorktreeRequest): Promise<proto.codemarie.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"createWorktree",
			request,
			proto.codemarie.CreateWorktreeRequest.toJSON,
			proto.codemarie.WorktreeResult.fromJSON,
		)
	}
	static async deleteWorktree(request: proto.codemarie.DeleteWorktreeRequest): Promise<proto.codemarie.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"deleteWorktree",
			request,
			proto.codemarie.DeleteWorktreeRequest.toJSON,
			proto.codemarie.WorktreeResult.fromJSON,
		)
	}
	static async switchWorktree(request: proto.codemarie.SwitchWorktreeRequest): Promise<proto.codemarie.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"switchWorktree",
			request,
			proto.codemarie.SwitchWorktreeRequest.toJSON,
			proto.codemarie.WorktreeResult.fromJSON,
		)
	}
	static async getAvailableBranches(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.BranchList> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getAvailableBranches",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.BranchList.fromJSON,
		)
	}
	static async getWorktreeDefaults(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.WorktreeDefaults> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getWorktreeDefaults",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.WorktreeDefaults.fromJSON,
		)
	}
	static async getWorktreeIncludeStatus(request: proto.codemarie.EmptyRequest): Promise<proto.codemarie.WorktreeIncludeStatus> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getWorktreeIncludeStatus",
			request,
			proto.codemarie.EmptyRequest.toJSON,
			proto.codemarie.WorktreeIncludeStatus.fromJSON,
		)
	}
	static async createWorktreeInclude(
		request: proto.codemarie.CreateWorktreeIncludeRequest,
	): Promise<proto.codemarie.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"createWorktreeInclude",
			request,
			proto.codemarie.CreateWorktreeIncludeRequest.toJSON,
			proto.codemarie.WorktreeResult.fromJSON,
		)
	}
	static async checkoutBranch(request: proto.codemarie.CheckoutBranchRequest): Promise<proto.codemarie.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"checkoutBranch",
			request,
			proto.codemarie.CheckoutBranchRequest.toJSON,
			proto.codemarie.WorktreeResult.fromJSON,
		)
	}
	static async mergeWorktree(request: proto.codemarie.MergeWorktreeRequest): Promise<proto.codemarie.MergeWorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"mergeWorktree",
			request,
			proto.codemarie.MergeWorktreeRequest.toJSON,
			proto.codemarie.MergeWorktreeResult.fromJSON,
		)
	}
	static async trackWorktreeViewOpened(
		request: proto.codemarie.TrackWorktreeViewOpenedRequest,
	): Promise<proto.codemarie.Empty> {
		return WorktreeServiceClient.makeUnaryRequest(
			"trackWorktreeViewOpened",
			request,
			proto.codemarie.TrackWorktreeViewOpenedRequest.toJSON,
			proto.codemarie.Empty.fromJSON,
		)
	}
}
